build_mau:
  outputs:
    dev:
      account: MLB09869
      database: dev
      password: AbHInav_9867
      role: accountadmin
      schema: analytics
      threads: 1
      type: snowflake
      user: abhinav
      warehouse: compute_wh
  target: dev
